### ISSUE TITLE
Lỗi về mã khi thử cài đặt ở phần training

### ISSUE THREAD

**Issue by HoangMinh991** [pbcquoc/yolo#1]
Vì máy yếu nên em thử với bộ dữ liệu bé để xem cách thuật toán hoạt động nhưng lại vấp lỗi này
![image](https://user-images.githubusercontent.com/46933995/51550328-ff265600-1e20-11e9-9a22-96ab14271968.png)

**Comment by pbcquoc** [comment]
lỗi này là do train_total_loss chưa được gán nhé em. anh nghĩ là do tập dữ liệu em nhỏ quá, nên model chưa loop để train vì len(X_train)//batch_size = 0

**Comment by HoangMinh991** [comment]
Để em thử full tập dữ liệu lên colaboratory xem sao.
Cảm ơn a rất nhiều

Vào 12:05 SA, Th 4, 23 thg 1, 2019 Pham Ba Cuong Quoc <
notifications@github.com đã viết:
